<?php
return [
    //S&E Registers forms
    'Punjab' => [
        'form-a' => 'S&E Registers/punjab/child.php',
        'form-ii-a' => 'S&E Registers/punjab/form_ii_a.php',
        'form-xii' => 'S&E Registers/punjab/clra.php',
        'form-lwf-fine' => 'S&E Registers/punjab/lwf_fine.php',
        'form-lwf-wage' => 'S&E Registers/punjab/lwf_wage.php',
        'form-mb-act' => 'S&E Registers/punjab/mb_act.php',
        'form-mw-damage' => 'S&E Registers/punjab/mw_damage.php',
        'form-mw-fine' => 'S&E Registers/punjab/mw_fine.php',
        'form-mw-musterroll' => 'S&E Registers/punjab/mw_musterroll.php',
        'form-mw-wage' => 'S&E Registers/punjab/mw_wage.php',
        'form-ot-register' => 'S&E Registers/punjab/ot_register.php',
        'form-se-damage' => 'S&E Registers/punjab/se_damage.php',
        'form-se-musterroll' => 'S&E Registers/punjab/se_musterroll.php',
        'form-se-wage' => 'S&E Registers/punjab/se_wage.php',
        'form-various-acts' => 'S&E Registers/punjab/variousacts.php',
    ],

    'Gujarat' => [
        'form-advance' => 'S&E Registers/gujarat/advance.php',
        'form-child-labour' => 'S&E Registers/gujarat/Child Labour.php',
        'form-clra' => 'S&E Registers/gujarat/CLRA.php',
        'form-lwf-b' => 'S&E Registers/gujarat/LWF Fine Form B.php',
        'form-lwf-a' => 'S&E Registers/gujarat/LWF Wage Form A.php',
        'form-maternity-a' => 'S&E Registers/gujarat/Maternity A.php',
        'form-maternity-m' => 'S&E Registers/gujarat/Maternity M.php',
        'form-maternity-n' => 'S&E Registers/gujarat/Maternity N.php',
        'form-mw-damage-loss' => 'S&E Registers/gujarat/MW Damage Loss.php',
        'form-mw-musterroll' => 'S&E Registers/gujarat/MW Musterroll.php',
        'form-mw-wage-slip' => 'S&E Registers/gujarat/MW Wage Slip.php',
        'form-mw-wage' => 'S&E Registers/gujarat/MW Wage.php',
        'form-ot-register' => 'S&E Registers/gujarat/OT Register.php',
        'form-se-leave-accumulation' => 'S&E Registers/gujarat/SE Leave Accumulation.php',
        'form-se-leave-book' => 'S&E Registers/gujarat/SE Leave Book.php',
        'form-se-musterroll' => 'S&E Registers/gujarat/se_musterroll.php',
        'form-various' => 'S&E Registers/gujarat/variousacts.php',
    ],


    'Jharkhand' => [
        'form-advance' => 'S&E Registers/jharkhand/Advance.php',
        'form-child' => 'S&E Registers/jharkhand/Child.php',
        'form-clra' => 'S&E Registers/jharkhand/CLRA.php',
        'form-mb-act' => 'S&E Registers/jharkhand/MB_Act.php',
        'form-mw-damage' => 'S&E Registers/jharkhand/MW_Damage.php',
        'form-mw-musterroll' => 'S&E Registers/jharkhand/MW_Musterroll.php',
        'form-ot-register' => 'S&E Registers/jharkhand/OT_Register.php',
        'form-se-leave-register' => 'S&E Registers/jharkhand/SE Leave Register.php',
        'form-se-service-card' => 'S&E Registers/jharkhand/SE Service Card.php',
        'form-se-wage-register' => 'S&E Registers/jharkhand/SE Wage Register.php',
        'form-se-damage' => 'S&E Registers/jharkhand/SE_Damage.php',
        'form-various-act' => 'S&E Registers/jharkhand/Various Act.php',
    ],

    'Assam' => [
        'form-advance' => 'S&E Registers/assam/Advance.php',
        'form-child-labour' => 'S&E Registers/assam/Child Labour.php',
        'form-clra' => 'S&E Registers/assam/CLRA.php',
        'form-conf-per-workmen-register' => 'S&E Registers/assam/Conf.Per.Workmen Register.php',
        'form-maternity-a' => 'S&E Registers/assam/Maternity A.php',
        'form-mw-damage-loss' => 'S&E Registers/assam/MW Damage Loss.php',
        'form-mw-fine' => 'S&E Registers/assam/MW Fine.php',
        'form-mw-musterroll' => 'S&E Registers/assam/MW Musterroll.php',
        'form-mw-wage' => 'S&E Registers/assam/MW Wage.php',
        'form-ot-register' => 'S&E Registers/assam/OT Register.php',
        'form-se-leave-register' => 'S&E Registers/assam/SE Leave Register.php',
        'form-se-lime-washing' => 'S&E Registers/assam/SE Lime Washing.php',
        'form-se-musterroll' => 'S&E Registers/assam/se_musterroll.php',
        'form-various-act' => 'S&E Registers/assam/variousacts.php',
        'form-workman-register' => 'S&E Registers/assam/Workman Register.php',
    ],

    'Delhi' => [
        'form-Child-Labour' => 'S&E Registers/Delhi/Child Labour.php',
        'form-clra' => 'S&E Registers/Delhi/CLRA.php',
        'form-lwf-fine' => 'S&E Registers/Delhi/LWF Fine.php',
        'form-lwf-wage' => 'S&E Registers/Delhi/LWF Wage.php',
        'form-maternity-a' => 'S&E Registers/Delhi/Maternity A.php',
        'form-mw-damage-loss' => 'S&E Registers/Delhi/MW Damage Loss.php',
        'form-mw-musterroll' => 'S&E Registers/Delhi/MW Musterroll.php',
        'form-mw-fine' => 'S&E Registers/Delhi/MW Fine.php',
        'form-mw-wage' => 'S&E Registers/Delhi/MW Wage.php',
        'form-ot-register' => 'S&E Registers/Delhi/OT Register.php',
        'form-various' => 'S&E Registers/Delhi/variousacts.php',
    ],

    'Haryana' => [
        'form-a' => 'S&E Registers/Haryana forms/child.php',
        'form-ii-a' => 'S&E Registers/Haryana forms/advance.php',
        'form-xii' => 'S&E Registers/Haryana forms/clra.php',
        'form-lwf-fine' => 'S&E Registers/Haryana forms/lwf_fine.php',
        'form-lwf-wage' => 'S&E Registers/Haryana forms/lwf_wage.php',
        'form-mb-act' => 'S&E Registers/Haryana forms/mb_act.php',
        'form-mw-damage' => 'S&E Registers/Haryana forms/mw_damage.php',
        'form-mw-fine' => 'S&E Registers/Haryana forms/mw_fine.php',
        'form-mw-musterroll' => 'S&E Registers/Haryana forms/mw_musterroll.php',
        'form-mw-wage' => 'S&E Registers/Haryana forms/mw_wage.php',
        'form-ot-register' => 'S&E Registers/Haryana forms/ot_register.php',
        'form-se-damage' => 'S&E Registers/Haryana forms/se_damage.php',
        'form-se-musterroll' => 'S&E Registers/Haryana forms/se_musterroll.php',
        'form-se-wage' => 'S&E Registers/Haryana forms/se_wage.php',
        'form-various-acts' => 'S&E Registers/Haryana forms/variousacts.php',
    ],


    'Goa' => [
        'form-child-labour' => 'S&E Registers/Goa/Child Labour.php',
        'form-clra' => 'S&E Registers/Goa/CLRA.php',
        'form-lwf-fine' => 'S&E Registers/Goa/LWF Fine.php',
        'form-lwf-wage' => 'S&E Registers/Goa/LWF Wage.php',
        'form-maternity-a' => 'S&E Registers/Goa/Maternity A.php',
        'form-ot-register' => 'S&E Registers/Goa/OT Register.php',
        'form-se-advance' => 'S&E Registers/Goa/SE Advance.php',
        'form-se-damage-loss' => 'S&E Registers/Goa/SE Damage Loss.php',
        'form-se-fine-register' => 'S&E Registers/Goa/SE Fine Register.php',
        'form-se-leave-register' => 'S&E Registers/Goa/SE Leave Register.php',
        'form-se-musterroll' => 'S&E Registers/Goa/SE Musterroll.php',
        'form-se-wage' => 'S&E Registers/Goa/SE Wage.php',
        'form-variousacts' => 'S&E Registers/Goa/Variousacts.php',
    ],

    'Himachal pradesh' => [
        'form-child-labour' => 'S&E Registers/Himachal pradesh/Child Labour.php',
        'form-clra' => 'S&E Registers/Himachal pradesh/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Himachal pradesh/Maternity A.php',
        'form-mw-damage-loss' => 'S&E Registers/Himachal pradesh/MW Damage Loss.php',
        'form-mw-fine' => 'S&E Registers/Himachal pradesh/MW Fine.php',
        'form-ot-register' => 'S&E Registers/Himachal pradesh/OT_Register.php',
        'form-se-deduction-register' => 'S&E Registers/Himachal pradesh/SE Deduction Register.php',
        'form-se-leave-register-8' => 'S&E Registers/Himachal pradesh/SE Leave Register 8.php',
        'form-se-leave-register-11' => 'S&E Registers/Himachal pradesh/SE Leave Register 11.php',
        'form-se-wage-register' => 'S&E Registers/Himachal pradesh/SE Wage Register.php',
        'form-variousacts' => 'S&E Registers/Himachal pradesh/Variousacts.php',
    ],

    'Andhra pradesh' => [
        'form-child-labour' => 'S&E Registers/Andhra pradesh/Child Labour.php',
        'form-clra' => 'S&E Registers/Andhra pradesh/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Andhra pradesh/Maternity A.php',
        'lwf-fine-regiter' => 'S&E Registers/Andhra pradesh/LWF Fine Register.php',
        'lwf-wage-regiter' => 'S&E Registers/Andhra pradesh/LWF Wage Register.php',
        'form-mw-damage' => 'S&E Registers/Andhra pradesh/MW_Damage.php',
        'form-mw-fine' => 'S&E Registers/Andhra pradesh/MW_Fine.php',
        'form-mw-musterroll' => 'S&E Registers/Andhra pradesh/MW_Musterroll.php',
        'form-ot-register' => 'S&E Registers/Andhra pradesh/OT Register.php',
        'form-mw-wage-register' => 'S&E Registers/Andhra pradesh/MW_Wage Register.php',
        'form-mw-wage-slip' => 'S&E Registers/Andhra pradesh/MW Wage Slip.php',
        'form-se-advance' => 'S&E Registers/Andhra pradesh/SE Advance.php',
        'form-se-damage-loss' => 'S&E Registers/Andhra pradesh/SE Damage Loss.php',
        'form-se-fine-register' => 'S&E Registers/Andhra pradesh/SE Fine Register.php',
        'form-se-leave-register' => 'S&E Registers/Andhra pradesh/SE Leave Register.php',
        'form-se-musterroll' => 'S&E Registers/Andhra pradesh/SE Musterroll.php',
        'form-se-wage-register' => 'S&E Registers/Andhra pradesh/SE Wage Register.php',
        'form-variousacts' => 'S&E Registers/Andhra pradesh/Variousacts.php',
    ],
    'Rajastan' => [
        'form-advance' => 'S&E Registers/Rajastan/advance.php',
        'form-child' => 'S&E Registers/Rajastan/child.php',
        'form-clra' => 'S&E Registers/Rajastan/clra.php',
        'form-maternity-a' => 'S&E Registers/Rajastan/Maternity A.php',
        'form-mw-damage' => 'S&E Registers/Rajastan/mw_damage.php',
        'form-mw-fine' => 'S&E Registers/Rajastan/mw_fine.php',
        'form-mw-wage' => 'S&E Registers/Rajastan/mw_wage.php',
        'form-ot-register' => 'S&E Registers/Rajastan/ot_register.php',
        'form-variousacts' => 'S&E Registers/Rajastan/variousacts.php',
        'form-se-maternity' => 'S&E Registers/Rajastan/SE_Maternity.php',
        'form-se-register-of-employement' => 'S&E Registers/Rajastan/SE_Register Of Employement.php',
        'form-se-register-of-leave-with-wages' => 'S&E Registers/Rajastan/SE_Register Of Leave With Wages.php',
    ],

    'Chattisgarh' => [
        'form-child-labour' => 'S&E Registers/Chattisgarh/Child Labour.php',
        'form-clra' => 'S&E Registers/Chattisgarh/CLRA.php',
        'form-lwf-fine' => 'S&E Registers/Chattisgarh/LWF Fine.php',
        'form-maternity-a' => 'S&E Registers/Chattisgarh/Maternity A.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Chattisgarh/MW Damage Loss.php',
        'form-se-leave-register-i' => 'S&E Registers/Chattisgarh/SE Leave Register Form I.php',
        'form-se-leave-register-j' => 'S&E Registers/Chattisgarh/SE Leave Register Form J.php',
        'form-se-lime-washing' => 'S&E Registers/Chattisgarh/SE Lime Washing.php',
        'form-se-muster-cum-wage' => 'S&E Registers/Chattisgarh/SE Muster Cum Wage.php',
        'form-variousacts' => 'S&E Registers/Chattisgarh/Variousacts.php',
    ],

    'Bihar' => [
        'form-advance' => 'S&E Registers/Bihar forms/Advance.php',
        'form-child' => 'S&E Registers/Bihar forms/Child.php',
        'form-clra' => 'S&E Registers/Bihar forms/CLRA.php',
        'form-mb-act' => 'S&E Registers/Bihar forms/MB_Act.php',
        'form-mw-damage' => 'S&E Registers/Bihar forms/MW_Damage.php',
        'form-mw-musterroll' => 'S&E Registers/Bihar forms/MW_Musterroll.php',
        'form-ot-register' => 'S&E Registers/Bihar forms/OT_Register.php',
        'form-se-leave-register' => 'S&E Registers/Bihar forms/SE Leave Register.php',
        'form-se-wage-register' => 'S&E Registers/Bihar forms/SE Wage Register.php',
        'form-se-damage' => 'S&E Registers/Bihar forms/SE_Damage.php',
        'form-variousacts' => 'S&E Registers/Bihar forms/Various Act.php',
    ],

    'Madhya pradesh' => [
        'form-child-labour' => 'S&E Registers/Madhya Pradesh/Child Labour.php',
        'form-clra' => 'S&E Registers/Madhya Pradesh/CLRA.php',
        'form-lwf-fine' => 'S&E Registers/Madhya Pradesh/lwf_fine.php',
        'form-maternity-a' => 'S&E Registers/Madhya Pradesh/Maternity A.php',
        'form-mw-damage-loss' => 'S&E Registers/Madhya Pradesh/MW Damage Loss.php',
        'form-se-leave-register-i' => 'S&E Registers/Madhya Pradesh/SE Leave Register Form I.php',
        'form-se-leave-register-j' => 'S&E Registers/Madhya Pradesh/SE Leave Register Form J.php',
        'form-se-lime-washing' => 'S&E Registers/Madhya Pradesh/SE Lime Washing.php',
        'form-se-musterroll' => 'S&E Registers/Madhya Pradesh/SE Muster Cum Wage Form N.php',
        'form-various-act' => 'S&E Registers/Madhya Pradesh/variousacts.php',
    ],

    'Uttarkhand' => [
        'form-advance' => 'S&E Registers/Uttarkhand/Advance.php',
        'form-child-labour' => 'S&E Registers/Uttarkhand/Child Labour.php',
        'form-clra' => 'S&E Registers/Uttarkhand/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Uttarkhand/Maternity A.php',
        'form-mw-damage' => 'S&E Registers/Uttarkhand/MW Damage or loss.php',
        'form-mw-fine' => 'S&E Registers/Uttarkhand/MW Fine.php',
        'form-mw-musterroll' => 'S&E Registers/Uttarkhand/MW Musterroll.php',
        'form-ot-register' => 'S&E Registers/Uttarkhand/MW OT Register.php',
        'form-mw-wage-slip' => 'S&E Registers/Uttarkhand/MW Wage Slip.php',
        'form-n&f-register' => 'S&E Registers/Uttarkhand/N&F Register.php',
        'form-se-damage-loss1' => 'S&E Registers/Uttarkhand/SE Damage Loss Form - D.php',
        'form-se-damage-loss' => 'S&E Registers/Uttarkhand/SE Damage Loss Form - E.php',
        'form-se-leave-register' => 'S&E Registers/Uttarkhand/SE Leave Register.php',
        'form-se-mustercumwage' => 'S&E Registers/Uttarkhand/SE Muster Cum Wage.php',
        'form-variousacts' => 'S&E Registers/Uttarkhand/Variousacts.php',
    ],

    'Uttar pradesh' => [
        'form-advance' => 'S&E Registers/Uttar pradesh/Advance.php',
        'form-child-labour' => 'S&E Registers/Uttar pradesh/Child Labour.php',
        'form-clra' => 'S&E Registers/Uttar pradesh/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Uttar pradesh/Maternity A.php',
        'form-mw-damage' => 'S&E Registers/Uttar pradesh/MW Damage or loss.php',
        'form-mw-fine' => 'S&E Registers/Uttar pradesh/MW Fine.php',
        'form-mw-musterroll' => 'S&E Registers/Uttar pradesh/MW Musterroll.php',
        'form-mw-ot-register' => 'S&E Registers/Uttar pradesh/MW OT Register.php',
        'form-mw-wage-slip' => 'S&E Registers/Uttar pradesh/MW Wage Slip.php',
        'form-mw-wage' => 'S&E Registers/Uttar pradesh/MW Wage.php',
        'form-n&f-register' => 'S&E Registers/Uttar pradesh/N&F Register.php',
        'form-se-damage-loss1' => 'S&E Registers/Uttar pradesh/SE Damage or Loss Form - D.php',
        'form-se-damage-loss' => 'S&E Registers/Uttar pradesh/SE Damage or Loss Form - E.php',
        'form-se-leave-register' => 'S&E Registers/Uttar pradesh/SE Leave Register.php',
        'form-se-mustercumwage' => 'S&E Registers/Uttar pradesh/SE Muster Cum Wage.php',
        'form-variousacts' => 'S&E Registers/Uttar pradesh/Variousacts.php',
    ],

    'Karnataka' => [
        'form-child' => 'S&E Registers/Karnataka/Child.php',
        'form-clra' => 'S&E Registers/Karnataka/CLRA.php',
        'form-combined-register' => 'S&E Registers/Karnataka/Combined Register.php',
        'form-lwf-fine-register' => 'S&E Registers/Karnataka/LWF Fine Register.php',
        'form-lwf-wage-register' => 'S&E Registers/Karnataka/LWF Wage Register.php',
        'form-maternity-a' => 'S&E Registers/Karnataka/Maternity A.php',
        'form-mw-wage-slips' => 'S&E Registers/Karnataka/MW Wage Slips.php',
        'form-se-leave-register-f' => 'S&E Registers/Karnataka/SE Leave Register F.php',
        'form-se-leave-register-h' => 'S&E Registers/Karnataka/SE Leave Register H.php',
        'form-se-mustercumwage-part1' => 'S&E Registers/Karnataka/SE MusterCumWage_Part1.php',
        'form-se-mustercumwage-part2' => 'S&E Registers/Karnataka/SE MusterCumWage_Part2.php',
        'form-suspension-register' => 'S&E Registers/Karnataka/Suspension Register.php',
        'form-various-act' => 'S&E Registers/Karnataka/Various Act.php',
    ],

    'Maharashtra' => [
        'form-child' => 'S&E Registers/Maharashtra/Child.php',
        'form-clra' => 'S&E Registers/Maharashtra/CLRA.php',
        'form-hra-a' => 'S&E Registers/Maharashtra/HRA Form A.php',
        'form-hra-i' => 'S&E Registers/Maharashtra/HRA Form I.php',
        'form-lwf-wage' => 'S&E Registers/Maharashtra/LWF Wage.php',
        'form-maternity-register' => 'S&E Registers/Maharashtra/Maternity Register.php',
        'form-mw-wage-slip' => 'S&E Registers/Maharashtra/MW Wage Slip.php',
        'form-advance-register' => 'S&E Registers/Maharashtra/Advance Register.php',
        'form-se-leave-accumulation' => 'S&E Registers/Maharashtra/SE Leave Accumulation.php',
        'form-se-leave-book' => 'S&E Registers/Maharashtra/SE Leave Book.php',
        'form-se-mustercumwage-form Q-part-i' => 'S&E Registers/Maharashtra/SE MusterCumWage_Form Q_Part I.php',
        'form-se-mustercumwage-form Q-part-ii' => 'S&E Registers/Maharashtra/SE MusterCumWage_Form Q_Part II.php',
        'form-se-mustercumwage-part-i' => 'S&E Registers/Maharashtra/SE MusterCumWage_Part I.php',
        'form-se-mustercumwage-part-ii' => 'S&E Registers/Maharashtra/SE MusterCumWage_Part II.php',
        'form-various-act' => 'S&E Registers/Maharashtra/Various Act.php',
        'form-lwf-fine' => 'S&E Registers/Maharashtra/LWF Fine Form C.php',
    ],

    'Telangana' => [
        'form-advance-register' => 'S&E Registers/Telangana/Advance Register.php',
        'form-child' => 'S&E Registers/Telangana/Child.php',
        'form-clra' => 'S&E Registers/Telangana/CLRA.php',
        'form-lwf-fine-register' => 'S&E Registers/Telangana/LWF Fine Register.php',
        'form-lwf-wage-register' => 'S&E Registers/Telangana/LWF Wage Register.php',
        'form-maternity-a' => 'S&E Registers/Telangana/Maternity A.php',
        'form-mw-ot-register' => 'S&E Registers/Telangana/MW Ot Register.php',
        'form-mw-deductions' => 'S&E Registers/Telangana/MW Register of Deductions.php',
        'form-mw-fine' => 'S&E Registers/Telangana/MW Register of Fines.php',
        'form-mw-wage-register' => 'S&E Registers/Telangana/MW Wage Register.php',
        'form-mw-wage-slip' => 'S&E Registers/Telangana/MW Wage Slip.php',
        'form-mw-musterroll' => 'S&E Registers/Telangana/MW_Musterroll.php',
        'form-nf-register' => 'S&E Registers/Telangana/N&F Register.php',
        'form-se-damage' => 'S&E Registers/Telangana/SE Damage or Loss.php',
        'form-se-fine-register' => 'S&E Registers/Telangana/SE Fine Register.php',
        'form-se-leave-register' => 'S&E Registers/Telangana/SE Leave Register.php',
        'form-se-musterroll' => 'S&E Registers/Telangana/SE Musterroll.php',
        'form-se-wage-register' => 'S&E Registers/Telangana/SE Wage Register.php',
        'form-variousacts-compliance' => 'S&E Registers/Telangana/Various Act Ease Compliance.php',
        'form-variousacts-formii' => 'S&E Registers/Telangana/Various Act Integrated_Form II.php',
        'form-variousacts-formiii' => 'S&E Registers/Telangana/Various Act Integrated_Form III.php',

    ],
    'Kerala' => [
        'form-child-labour' => 'S&E Registers/Kerala/Child Labour.php',
        'form-clra' => 'S&E Registers/Kerala/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Kerala/Maternity A.php',
        'form-mw-wage-slip' => 'S&E Registers/Kerala/MW Wage Slip.php',
        'form-mw-damage' => 'S&E Registers/Kerala/MW_Damage.php',
        'form-mw-fine' => 'S&E Registers/Kerala/MW_Fine.php',
        'form-mw-musterroll' => 'S&E Registers/Kerala/MW_Musterroll.php',
        'form-mw-wage-register' => 'S&E Registers/Kerala/MW_Wage Register.php',
        'form-nf-musterroll' => 'S&E Registers/Kerala/N&F Musterroll.php',
        'form-ot-register' => 'S&E Registers/Kerala/OT Register.php',
        'form-se-leave-register' => 'S&E Registers/Kerala/S&E Leave Register.php',
        'form-se-musterroll' => 'S&E Registers/Kerala/S&E Musterroll.php',
        'form-se-service-card' => 'S&E Registers/Kerala/S&E Service card.php',
        'form-se-advance' => 'S&E Registers/Kerala/SE Advance.php',
        'form-variousacts' => 'S&E Registers/Kerala/Variousacts.php',
    ],

    'Tamilnadu' => [
        'form-child-labour' => 'S&E Registers/Tamilnadu/Child Labour.php',
        'form-clra' => 'S&E Registers/Tamilnadu/CLRA.php',
        'form-conf-per-workmen-register' => 'S&E Registers/Tamilnadu/Conf.Per.Workmen Register.php',
        'form-lwf-wage' => 'S&E Registers/Tamilnadu/LWF Wage.php',
        'form-maternity-a' => 'S&E Registers/Tamilnadu/Maternity A.php',
        'form-mw-damage' => 'S&E Registers/Tamilnadu/MW_Damage.php',
        'form-mw-fine' => 'S&E Registers/Tamilnadu/MW_Fine.php',
        'form-mw-musterroll' => 'S&E Registers/Tamilnadu/MW_Musterroll.php',
        'form-mw-ot-register' => 'S&E Registers/Tamilnadu/MW OT Register.php',
        'form-mw-wage-register' => 'S&E Registers/Tamilnadu/MW_Wage Register.php',
        'form-mw-workman' => 'S&E Registers/Tamilnadu/MW Workman.php',
        'form-nf-register' => 'S&E Registers/Tamilnadu/N&F Register.php',
        'form-se-employee-register' => 'S&E Registers/Tamilnadu/SE Employee Register.php',
        'form-se-leave-register' => 'S&E Registers/Tamilnadu/SE Leave Register.php',
        'form-se-musterroll' => 'S&E Registers/Tamilnadu/SE Musterroll.php',
        'form-se-notice' => 'S&E Registers/Tamilnadu/SE Notice Working Hours.php',
        'form-se-wage' => 'S&E Registers/Tamilnadu/SE Wage.php',
        'form-se-wage-slip' => 'S&E Registers/Tamilnadu/SE Wage Slip.php',
        'form-variousacts' => 'S&E Registers/Tamilnadu/Variousacts.php',
    ],

    'Odisha' => [
        'form-child-labour' => 'S&E Registers/Odisha/Child.php',
        'form-clra' => 'S&E Registers/Odisha/CLRA.php',
        'form-lwf-fine-register-appendix' => 'S&E Registers/Odisha/LWF_Fine Register Appendix.php',
        'form-lwf-fine-register-e' => 'S&E Registers/Odisha/LWF_Fine Register E.php',
        'form-lwf-wage-register' => 'S&E Registers/Odisha/LWF_Wage Register.php',
        'form-maternity-register' => 'S&E Registers/Odisha/Maternity Register.php',
        'form-sea-leave-register' => 'S&E Registers/Odisha/SEA_Leave Register.php',
        'form-sea-mustercumwage' => 'S&E Registers/Odisha/SEA_MusterCumWage.php',
        'form-sea-ot-register' => 'S&E Registers/Odisha/SEA_OT Register.php',
        'form-variousact' => 'S&E Registers/Odisha/Various Act.php',
    ],

    'Jammu and kashmir' => [
        'form-child-labour' => 'S&E Registers/Jammu & Kashmir/Child.php',
        'form-clra' => 'S&E Registers/Jammu & Kashmir/CLRA.php',
        'form-maternity-register' => 'S&E Registers/Jammu & Kashmir/Maternity Register.php',
        'form-mw-fine' => 'S&E Registers/Jammu & Kashmir/MW_Fine.php',
        'form-mw-damage' => 'S&E Registers/Jammu & Kashmir/MW_Damage.php',
        'form-mwa-service-card' => 'S&E Registers/Jammu & Kashmir/MWA_Service Card.php',
        'form-advance-register' => 'S&E Registers/Jammu & Kashmir/Advance Register.php',
        'form-sea-leave-register' => 'S&E Registers/Jammu & Kashmir/SEA_Leave Register.php',
        'form-sea-leave-book' => 'S&E Registers/Jammu & Kashmir/SEA_Leave book.php',
        'form-sea-lime-washing' => 'S&E Registers/Jammu & Kashmir/SEA_Lime Washing.php',
        'form-sea-mustercumwage' => 'S&E Registers/Jammu & Kashmir/SEA_MusterCumWage.php',
        'form-variousact' => 'S&E Registers/Jammu & Kashmir/Various Act.php',
    ],

    'West bengal' => [
        'form-child' => 'S&E Registers/West Bengal/Child.php',
        'form-clra' => 'S&E Registers/West Bengal/CLRA.php',
        'form-hra' => 'S&E Registers/West Bengal/HRA Form A.php',
        'form-lwf-fine' => 'S&E Registers/West Bengal/LWF Fine Form B.php',
        'form-lwf-wage' => 'S&E Registers/West Bengal/LWF Wage Form A.php',
        'form-maternity-a' => 'S&E Registers/West Bengal/Maternity A.php',
        'form-mw-fine' => 'S&E Registers/West Bengal/MW Fine Form I.php',
        'form-mw-wage' => 'S&E Registers/West Bengal/MW Wage Form IX.php',
        'form-mwa-damage' => 'S&E Registers/West Bengal/MWA Damage Form II.php',
        'form-mwa-musterroll' => 'S&E Registers/West Bengal/MWA Musterroll.php',
        'form-mwa-ot' => 'S&E Registers/West Bengal/MWA OT Register.php',
        'form-mwa-wage-slip' => 'S&E Registers/West Bengal/MWA Wage slip.php',
        'form-mwa-workman' => 'S&E Registers/West Bengal/MWA Workman Register.php',
        'form-pwa-advance' => 'S&E Registers/West Bengal/PWA Advance.php',
        'form-se-musterroll' => 'S&E Registers/West Bengal/SE Musterroll.php',
        'form-sea-leave-register' => 'S&E Registers/West Bengal/SEA Leave Register.php',
        'form-sea-musterroll' => 'S&E Registers/West Bengal/SEA Musterroll.php',
        'form-sea-ot-register' => 'S&E Registers/West Bengal/SEA OT Register.php',
        'form-sea-wage' => 'S&E Registers/West Bengal/SEA Wage.php',
        'form-sea-workman-register' => 'S&E Registers/West Bengal/SEA Workman Register.php',
        'form-variousacts' => 'S&E Registers/West Bengal/Variousacts.php',
        'form-web-workman' => 'S&E Registers/West Bengal/WEB Workman.php',

    ],

    'Tripura' => [
        'form-child' => 'S&E Registers/Tripura/Child.php',
        'form-clra' => 'S&E Registers/Tripura/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Tripura/Maternity A.php',
        'form-mwa-fine' => 'S&E Registers/Tripura/MWA Fine Form I.php',
        'form-mwa-damage' => 'S&E Registers/Tripura/MWA Damage Form II.php',
        'form-se-musterroll' => 'S&E Registers/Tripura/SE Musterroll.php',
        'form-sea-ot-register' => 'S&E Registers/Tripura/SEA OT Register.php',
        'form-sea-workman-register' => 'S&E Registers/Tripura/SEA Workman Register.php',
        'form-sea-leave-register' => 'S&E Registers/Tripura/SEA Leave Register.php',
        'form-sea-wage' => 'S&E Registers/Tripura/SEA Wage.php',
        'form-variousacts' => 'S&E Registers/Tripura/Variousacts.php',
    ],

    'Manipur' => [
        'form-child' => 'S&E Registers/Manipur/Child.php',
        'form-clra' => 'S&E Registers/Manipur/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Manipur/Maternity A.php',
        'form-mw-ot' => 'S&E Registers/Manipur/MW OT Register.php',
        'form-mw-wage' => 'S&E Registers/Manipur/MW Wage.php',
        'form-mwa-fine' => 'S&E Registers/Manipur/MWA Fine Form I.php',
        'form-mwa-damage' => 'S&E Registers/Manipur/MWA Damage Form II.php',
        'form-mwa-musterroll' => 'S&E Registers/Manipur/MWA Musterroll.php',
        'form-sea-attendance-register' => 'S&E Registers/Manipur/SEA Attendance Register.php',
        'form-sea-fine-register' => 'S&E Registers/Manipur/SEA Fine Register.php',
        'form-sea-leave-register' => 'S&E Registers/Manipur/SEA Leave Register.php',
        'form-sea-wage-register' => 'S&E Registers/Manipur/SEA Wage Register.php',
        'form-variousacts' => 'S&E Registers/Manipur/Variousacts.php',
    ],


    'Pondicherry' => [
        'form-child' => 'S&E Registers/Pondicherry/Child.php',
        'form-clra' => 'S&E Registers/Pondicherry/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Pondicherry/Maternity A.php',
        'form-mw-ot' => 'S&E Registers/Pondicherry/MW OT Register.php',
        'form-n&f-register' => 'S&E Registers/Pondicherry/N&F Register.php',
        'form-se-advance' => 'S&E Registers/Pondicherry/SE Advance Register.php',
        'form-se-musterroll' => 'S&E Registers/Pondicherry/SE Musterroll.php',
        'form-se-wage-register' => 'S&E Registers/Pondicherry/SE Wage Register.php',
        'form-variousacts' => 'S&E Registers/Pondicherry/Variousacts.php',

    ],

    'Sikkim' => [
        'form-child' => 'S&E Registers/Sikkim/Child.php',
        'form-clra' => 'S&E Registers/Sikkim/CLRA.php',
        'form-maternity-a' => 'S&E Registers/Sikkim/Maternity A.php',
        'form-mw-wage' => 'S&E Registers/Sikkim/MW Wage Form IX.php',
        'form-mwa-fine' => 'S&E Registers/Sikkim/MWA Fine Form I.php',
        'form-mwa-damage' => 'S&E Registers/Sikkim/MWA Damage Form II.php',
        'form-mwa-ot' => 'S&E Registers/Sikkim/MWA OT Register.php',
        'form-mwa-musterroll' => 'S&E Registers/Sikkim/MWA Musterroll.php',
        'form-mwa-workman' => 'S&E Registers/Sikkim/MWA Workman Register.php',
        'form-variousacts' => 'S&E Registers/Sikkim/Variousacts.php',

    ],

    'Mizoram' => [
        'form-child' => 'S&E Registers/Mizoram/Child.php',
        'form-clra' => 'S&E Registers/Mizoram/CLRA.php',
        'form-h-overtime-register' => 'S&E Registers/Mizoram/Form_H_Overtime_Register.php',
        'form-mb-musterroll-form-a' => 'S&E Registers/Mizoram/MB_Musterroll_Form_A.php',
        'form-mw-wage-register' => 'S&E Registers/Mizoram/MW_Wage_Register.php',
        'form-mwa-fine' => 'S&E Registers/Mizoram/MWA_Fine.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Mizoram/MW_Damage_or_Loss.php',
        'form-mw-ot-register' => 'S&E Registers/Mizoram/MW_OT_Register.php',
        'form-mw-musterroll' => 'S&E Registers/Mizoram/MW_Musterroll.php',
        'form-se-musterroll' => 'S&E Registers/Mizoram/SE Musterroll.php',
        'form-se-lime-washing' => 'S&E Registers/Mizoram/SE_Lime_Washing.php',
        'form-se-workmen-register' => 'S&E Registers/Mizoram/SE_WorkmenRegister.php',
        'form-se-leave-register' => 'S&E Registers/Mizoram/SE_Leave_Register.php',
        'form-variousact' => 'S&E Registers/Mizoram/Various_act.php',
    ],

    'Meghalaya' => [
        'form-child' => 'S&E Registers/Meghalaya/Child.php',
        'form-clra' => 'S&E Registers/Meghalaya/CLRA.php',
        'form-mb-musterroll-form-a' => 'S&E Registers/Meghalaya/MB Musterroll Form A.php',
        'form-mw-wage-register' => 'S&E Registers/Meghalaya/MW Wage Register.php',
        'form-mwa-fine' => 'S&E Registers/Meghalaya/MWA Fine.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Meghalaya/MW Damage or Loss.php',
        'form-mw-ot-register' => 'S&E Registers/Meghalaya/MW OT Register.php',
        'form-mw-musterroll' => 'S&E Registers/Meghalaya/MW Musterroll.php',
        'form-se-musterroll' => 'S&E Registers/Meghalaya/SE Musterroll.php',
        'form-se-ot-register' => 'S&E Registers/Meghalaya/SE OT Register.php',
        'form-se-lime-washing' => 'S&E Registers/Meghalaya/SE Lime Washing.php',
        'form-se-register-of-employment' => 'S&E Registers/Meghalaya/SE Register Of Employment.php',
        'form-se-leave-register' => 'S&E Registers/Meghalaya/SE Leave Register.php',
        'form-variousact' => 'S&E Registers/Meghalaya/Various act.php',
    ],


    'Nagaland' => [
        'form-child' => 'S&E Registers/Nagaland/Child.php',
        'form-clra' => 'S&E Registers/Nagaland/CLRA.php',
        'form-mb-musterroll-form-a' => 'S&E Registers/Nagaland/MB Musterroll Form A.php',
        'form-mw-wage-register' => 'S&E Registers/Nagaland/MW Wage Register.php',
        'form-mwa-fine' => 'S&E Registers/Nagaland/MWA Fine.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Nagaland/MW Damage or Loss.php',
        'form-mw-ot-register' => 'S&E Registers/Nagaland/MW OT Register.php',
        'form-mw-musterroll' => 'S&E Registers/Nagaland/MW Musterroll.php',
        'form-variousact' => 'S&E Registers/Nagaland/Various act.php',
    ],

    'Arunachal pradesh' => [
        'form-child' => 'S&E Registers/Arunachal Pradesh/Child.php',
        'form-clra' => 'S&E Registers/Arunachal Pradesh/CLRA.php',
        'form-mb-musterroll-form-a' => 'S&E Registers/Arunachal Pradesh/MB Musterroll Form A.php',
        'form-mw-wage-register' => 'S&E Registers/Arunachal Pradesh/MW Wage Register.php',
        'form-mwa-fine' => 'S&E Registers/Arunachal Pradesh/MWA Fine.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Arunachal Pradesh/MW Damage or Loss.php',
        'form-mw-ot-register' => 'S&E Registers/Arunachal Pradesh/MW OT Register.php',
        'form-mw-musterroll' => 'S&E Registers/Arunachal Pradesh/MW Musterroll.php',
        'form-variousact' => 'S&E Registers/Arunachal Pradesh/Various act.php',
    ],

    'Chandigarh' => [
        'form-a' => 'S&E Registers/Chandigarh/child.php',
        'form-ii-a' => 'S&E Registers/Chandigarh/form_ii_a.php',
        'form-xii' => 'S&E Registers/Chandigarh/clra.php',
        'form-lwf-fine' => 'S&E Registers/Chandigarh/lwf_fine.php',
        'form-lwf-wage' => 'S&E Registers/Chandigarh/lwf_wage.php',
        'form-mb-act' => 'S&E Registers/Chandigarh/mb_act.php',
        'form-mw-damage' => 'S&E Registers/Chandigarh/mw_damage.php',
        'form-mw-fine' => 'S&E Registers/Chandigarh/mw_fine.php',
        'form-mw-musterroll' => 'S&E Registers/Chandigarh/mw_musterroll.php',
        'form-mw-wage' => 'S&E Registers/Chandigarh/mw_wage.php',
        'form-ot-register' => 'S&E Registers/Chandigarh/ot_register.php',
        'form-se-damage' => 'S&E Registers/Chandigarh/se_damage.php',
        'form-se-musterroll' => 'S&E Registers/Chandigarh/se_musterroll.php',
        'form-se-wage' => 'S&E Registers/Chandigarh/se_wage.php',
        'form-various-acts' => 'S&E Registers/Chandigarh/variousacts.php',
    ],

    'Lakshadweep' => [
        'form-clra' => 'S&E Registers/Lakshadweep/CLRA.php',
        'form-maternity-form-a' => 'S&E Registers/Lakshadweep/Maternity_Form_A.php',
        'form-mw-wage-register' => 'S&E Registers/Lakshadweep/MW_Wage_Register.php',
        'form-mwa-fine' => 'S&E Registers/Lakshadweep/MWA_Fine.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Lakshadweep/MW_Damage_or_Loss.php',
        'form-mw-ot-register' => 'S&E Registers/Lakshadweep/MW_OT_Register.php',
        'form-mw-musterroll' => 'S&E Registers/Lakshadweep/MW_Musterroll.php',
        'form-variousact' => 'S&E Registers/Lakshadweep/Various_act.php',
    ],

    'Andaman and nicobar' => [
        'form-child' => 'S&E Registers/Andaman and Nicobar/Child.php',
        'form-clra' => 'S&E Registers/Andaman and Nicobar/CLRA.php',
        'form-act-form-a' => 'S&E Registers/Andaman and Nicobar/MB Act Form A.php',
        'form-mwa-fine' => 'S&E Registers/Andaman and Nicobar/MWA Fine.php',
        'form-mwa-damage-or-loss' => 'S&E Registers/Andaman and Nicobar/MWA Damage or Loss.php',
        'form-se-workman-register' => 'S&E Registers/Andaman and Nicobar/SE Workman Register.php',
        'form-se-wage' => 'S&E Registers/Andaman and Nicobar/SE Wage.php',
        'form-se-ot-register' => 'S&E Registers/Andaman and Nicobar/SE OT Register.php',
        'form-sw-musterroll' => 'S&E Registers/Andaman and Nicobar/SW Musterroll.php',
        'form-variousact' => 'S&E Registers/Andaman and Nicobar/Various Act.php',
    ],

    'Dadra and nagra haveli' => [
        'form-child' => 'S&E Registers/Dadra & Nagra Haveli/Child.php',
        'form-clra' => 'S&E Registers/Dadra & Nagra Haveli/CLRA.php',
        'form-register-of-leave' => 'S&E Registers/Dadra & Nagra Haveli/Register_Of_Leave.php',
        'form-mb-musterroll-form-a' => 'S&E Registers/Dadra & Nagra Haveli/MB_Musterroll_Form_A.php',
        'form-mwa-ot-register' => 'S&E Registers/Dadra & Nagra Haveli/MWA_OT_Register.php',
        'form-se-fine-register' => 'S&E Registers/Dadra & Nagra Haveli/SE_Fine_Register.php',
        'form-se-lime-washinng' => 'S&E Registers/Dadra & Nagra Haveli/SE_Lime_Washing.php',
        'form-se-damage-or-loss' => 'S&E Registers/Dadra & Nagra Haveli/SE_Damage_or_Loss.php',
        'form-advance-register' => 'S&E Registers/Dadra & Nagra Haveli/Advance Register.php',
        'form-se-musterroll' => 'S&E Registers/Dadra & Nagra Haveli/SE_Musterroll.php',
        'form-se-wage-register' => 'S&E Registers/Dadra & Nagra Haveli/SE_Wage_Register.php',
        'form-variousact' => 'S&E Registers/Dadra & Nagra Haveli/Various_act.php',
    ],

    'Ladakh' => [
        'form-child' => 'S&E Registers/Ladakh/Child_Labour.php',
        'form-clra' => 'S&E Registers/Ladakh/CLRA.php',
        'form-mb-musterroll-form-a' => 'S&E Registers/Ladakh/MB_Musterroll_Form_A.php',
        'form-mw-wage-register' => 'S&E Registers/Ladakh/MW_Wage_Register.php',
        'form-mwa-fine' => 'S&E Registers/Ladakh/MWA_Fine.php',
        'form-mw-damage-or-loss' => 'S&E Registers/Ladakh/MW_Damage_or_Loss.php',
        'form-mw-ot-register' => 'S&E Registers/Ladakh/MW_OT_Register.php',
        'form-mw-musterroll' => 'S&E Registers/Ladakh/MW_Musterroll.php',
        'form-variousact' => 'S&E Registers/Ladakh/Various_Act.php',
        'form-sea-leave-register' => 'S&E Registers/Ladakh/SEA_Leave_Register.php',
        'form-sea-leave-book' => 'S&E Registers/Ladakh/SEA_Leave_book.php',
        'form-sea-lime-washing' => 'S&E Registers/Ladakh/SEA_Lime_Washing.php',
        'form-sea-mustercumwage' => 'S&E Registers/Ladakh/SEA_Muster_Cum_Wage.php',
    ],

];
