<?php
return [

    //CLRA Registers Forms
    'Andaman and nicobar' => [
        'form-a-employee-register' => 'CLRA Registers/Andaman and Nicobar/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Andaman and Nicobar/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Andaman and Nicobar/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Andaman and Nicobar/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Andaman and Nicobar/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Andaman and Nicobar/MBA Form A_Maternity.php',
    ],

    'Andhra pradesh' => [
        'form-a-employee-register' => 'CLRA Registers/Andhra Pradesh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Andhra Pradesh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Andhra Pradesh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Andhra Pradesh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Andhra Pradesh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Andhra Pradesh/MBA Form A_Maternity.php',
    ],

    'Arunachal pradesh' => [
        'form-a-employee-register' => 'CLRA Registers/Arunachal pradesh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Arunachal pradesh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Arunachal pradesh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Arunachal pradesh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Arunachal pradesh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Arunachal pradesh/MBA Form A_Maternity.php',
    ],

    'Bihar' => [
        'form-a-employee-register' => 'CLRA Registers/Bihar forms/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Bihar forms/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Bihar forms/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Bihar forms/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Bihar forms/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Bihar forms/MBA Form A_Maternity.php',
    ],

    'Chandigarh' => [
        'form-a-employee-register' => 'CLRA Registers/Chandigarh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Chandigarh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Chandigarh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Chandigarh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Chandigarh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Chandigarh/MBA Form A_Maternity.php',
    ],
    
    'Delhi' => [
        'form-esi' => 'CLRA Registers/Delhi/ESI_Form_11.php',
        'form-xiii' => 'CLRA Registers/Delhi/Form XIII.php',
        'form-xiv' => 'CLRA Registers/Delhi/Form XIV.php',
        'form-xix' => 'CLRA Registers/Delhi/Form XIX.php',
        'form-xv' => 'CLRA Registers/Delhi/Form XV.php',
        'form-xvi' => 'CLRA Registers/Delhi/Form XVI.php',
        'form-xx' => 'CLRA Registers/Delhi/Form XX.php',
        'form-xxi' => 'CLRA Registers/Delhi/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Delhi/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Delhi/Form XXIII.php',
        'form-a' => 'CLRA Registers/Delhi/Form_A.php',
        'form-b' => 'CLRA Registers/Delhi/Form_B.php',
        'form-c' => 'CLRA Registers/Delhi/Form_C.php',
        'form-d' => 'CLRA Registers/Delhi/Form_D.php',
        'form-mba-form-a' => 'CLRA Registers/Delhi/MBA Form_A.php',
        'form-sea-form-g' => 'CLRA Registers/Delhi/SEA Form_G.php',
    ],

    'Haryana' => [
        'form-esi' => 'CLRA Registers/Haryana/ESI_Form 11.php',
        'form-9' => 'CLRA Registers/Haryana/Form 9.php',
        'form-xiii' => 'CLRA Registers/Haryana/Form XIII Register of Wages.php',
        'form-xiv' => 'CLRA Registers/Haryana/Form XIV.php',
        'form-xix-overtime' => 'CLRA Registers/Haryana/Form XIX Overtime.php',
        'form-xix' => 'CLRA Registers/Haryana/Form XIX.php',
        'form-xv' => 'CLRA Registers/Haryana/Form XV.php',
        'form-a' => 'CLRA Registers/Haryana/Form_A (Part-A).php',
        'form-b' => 'CLRA Registers/Haryana/Form_B.php',
        'form-c' => 'CLRA Registers/Haryana/Form_C.php',
        'form-d' => 'CLRA Registers/Haryana/Form_D.php',
        'form-mba' => 'CLRA Registers/Haryana/MBA Form_A.php',
    ],

    'Karnataka' => [
        'form-esi' => 'CLRA Registers/Karnataka/ESI_Form_11.php',
        'form-xiii' => 'CLRA Registers/Karnataka/Form XIII.php',
        'form-xiv' => 'CLRA Registers/Karnataka/Form XIV.php',
        'form-xix' => 'CLRA Registers/Karnataka/Form XIX.php',
        'form-xv' => 'CLRA Registers/Karnataka/Form XV.php',
        'form-xvi' => 'CLRA Registers/Karnataka/Form XVI.php',
        'form-a' => 'CLRA Registers/Karnataka/Form_A.php',
        'form-b' => 'CLRA Registers/Karnataka/Form_B.php',
        'form-c' => 'CLRA Registers/Karnataka/Form_C.php',
        'form-d' => 'CLRA Registers/Karnataka/Form_D.php',
        'form-mba-form-a' => 'CLRA Registers/Karnataka/MBA Form_A.php',
        'form-xiv-wage-cum-musterroll' => 'CLRA Registers/Karnataka/Form XIV Wage Cum Musterroll.php',
        'form-xvii-wage-register' => 'CLRA Registers/Karnataka/Form XVII Wage Register.php',
        'form-xii-register-of-contractors' => 'CLRA Registers/Karnataka/Form XII_Register of Contractors.php',

    ],

    'Rajasthan' => [
        'form-x-employment-card' => 'CLRA Registers/Rajasthan/Form X_Employment Card.php',
        'form-xii-register-of-contractor' => 'CLRA Registers/Rajasthan/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Rajasthan/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Rajasthan/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Rajasthan/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Rajasthan/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Rajasthan/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Rajasthan/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Rajasthan/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Rajasthan/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Rajasthan/MBA Form A_Maternity.php',
    ],

    'Tamilnadu' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Tamilnadu/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Tamilnadu/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Tamilnadu/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Tamilnadu/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Tamilnadu/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Tamilnadu/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Tamilnadu/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Tamilnadu/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Tamilnadu/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Tamilnadu/MBA Form A_Maternity.php',
        'form-t-wage-slip' => 'CLRA Registers/Tamilnadu/Form T Wage Slip.php',
        'form-xxix-damage-loss' => 'CLRA Registers/Tamilnadu/Form XXIX Damage or Loss.php',
        'form-xxvi-register-of-employees' => 'CLRA Registers/Tamilnadu/Form XXVI Register of Employees.php',
        'form-xxviii-wage-slip' => 'CLRA Registers/Tamilnadu/Form XXVIII Wage Slip.php',
        'form-xxvii-wage-register' => 'CLRA Registers/Tamilnadu/Form XXVII Wage Register.php',
    ],

    'Gujarat' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Gujarat/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Gujarat/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Gujarat/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Gujarat/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Gujarat/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Gujarat/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Gujarat/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Gujarat/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Gujarat/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Gujarat/MBA Form A_Maternity.php',
    ],

    'Assam' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Assam/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Assam/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Assam/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Assam/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Assam/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Assam/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Assam/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Assam/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Assam/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Assam/MBA Form A_Maternity.php',
        'form-xvii-wage-register' => 'CLRA Registers/Assam/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Assam/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Assam/Form XVI.php',
        'form-xx' => 'CLRA Registers/Assam/Form XX.php',
        'form-xxi' => 'CLRA Registers/Assam/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Assam/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Assam/Form XXIII.php',
    ],

    'Chattisgarh' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Chattisgarh/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Chattisgarh/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Chattisgarh/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Chattisgarh/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Chattisgarh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Chattisgarh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Chattisgarh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Chattisgarh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Chattisgarh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Chattisgarh/MBA Form A_Maternity.php',
        'form-xvii-wage-register' => 'CLRA Registers/Chattisgarh/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Chattisgarh/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Chattisgarh/Form XVI.php',
        'form-xx' => 'CLRA Registers/Chattisgarh/Form XX.php',
        'form-xxi' => 'CLRA Registers/Chattisgarh/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Chattisgarh/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Chattisgarh/Form XXIII.php',
    ],

    'Goa' => [
        'form-ix-register-of-workman' => 'CLRA Registers/Goa/Form IX Register of Workman.php',
        'form-x-employee-card' => 'CLRA Registers/Goa/Form X Employee Card.php',
        'form-xii-musterroll' => 'CLRA Registers/Goa/Form XII Musterroll.php',
        'form-xiii-register-of-wages' => 'CLRA Registers/Goa/Form XIII Register of Wages.php',
        'form-xiv-employement-card' => 'CLRA Registers/Goa/Form XIV_Employment Card.php',
        'form-xiv-wages-cum-musterroll' => 'CLRA Registers/Goa/Form XIV Wages Cum Musterroll.php',
        'form-xv-service-certificate' => 'CLRA Registers/Goa/Form XV_Service Certificate.php',
        'form-xix-wage-slip' => 'CLRA Registers/Goa/Form XIX_Wage Slip.php',
        'form-xvii-register-of-fines' => 'CLRA Registers/Goa/Form XVII Register of Fines.php',
        'form-x-damages' => 'CLRA Registers/Goa/Form X Damages.php',
        'form-xviii-register-of-advance' => 'CLRA Registers/Goa/Form XVIII Register of Advance.php',
        'form-xvii-wage-register' => 'CLRA Registers/Goa/Form XVII Wage Register.php',
        'form-a-employee-register' => 'CLRA Registers/Goa/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Goa/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Goa/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Goa/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Goa/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Goa/MBA Form A_Maternity.php',
    ],

    'Himachal pradesh' => [
        'form-xiv-employement-card' => 'CLRA Registers/Himachal pradesh/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Himachal pradesh/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Himachal pradesh/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Himachal pradesh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Himachal pradesh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Himachal pradesh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Himachal pradesh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Himachal pradesh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Himachal pradesh/MBA Form A_Maternity.php',
        'form-xxvii-wage-register' => 'CLRA Registers/Himachal pradesh/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Himachal pradesh/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Himachal pradesh/Form XVI.php',
        'form-xx' => 'CLRA Registers/Himachal pradesh/Form XX.php',
        'form-xxi' => 'CLRA Registers/Himachal pradesh/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Himachal pradesh/Form XXII.php',
    ],

    'Kerala' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Kerala/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Kerala/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Kerala/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Kerala/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Kerala/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Kerala/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Kerala/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Kerala/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Kerala/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Kerala/MBA Form A_Maternity.php',
        'form-xxvii-wage-register' => 'CLRA Registers/Kerala/Form XXVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Kerala/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Kerala/Form XVI.php',
        'form-xx' => 'CLRA Registers/Kerala/Form XX.php',
        'form-xxi' => 'CLRA Registers/Kerala/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Kerala/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Kerala/Form XXIII.php',
    ],

    'Madhya pradesh' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Madhya Pradesh/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Madhya Pradesh/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Madhya Pradesh/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Madhya Pradesh/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Madhya Pradesh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Madhya Pradesh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Madhya Pradesh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Madhya Pradesh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Madhya Pradesh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Madhya Pradesh/MBA Form A_Maternity.php',
        'form-xvii-wage-register' => 'CLRA Registers/Madhya Pradesh/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Madhya Pradesh/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Madhya Pradesh/Form XVI.php',
        'form-xx' => 'CLRA Registers/Madhya Pradesh/Form XX.php',
        'form-xxi' => 'CLRA Registers/Madhya Pradesh/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Madhya Pradesh/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Madhya Pradesh/Form XXIII.php',
    ],

    'Punjab' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Punjab/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Punjab/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Punjab/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Punjab/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Punjab/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Punjab/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Punjab/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Punjab/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Punjab/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Punjab/MBA Form A_Maternity.php',
        'form-xvii-wage-register' => 'CLRA Registers/Punjab/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Punjab/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Punjab/Form XVI.php',
        'form-xx' => 'CLRA Registers/Punjab/Form XX.php',
        'form-xxi' => 'CLRA Registers/Punjab/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Punjab/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Punjab/Form XXIII.php',
    ],

    'Sikkim' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Sikkim/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Sikkim/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Sikkim/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Sikkim/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Sikkim/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Sikkim/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Sikkim/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Sikkim/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Sikkim/ESI Form 11_AccidentBook.php',
        'form-xvii-wage-register' => 'CLRA Registers/Sikkim/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Sikkim/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Sikkim/Form XVI.php',
        'form-xxii' => 'CLRA Registers/Sikkim/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Sikkim/Form XXIII.php',
        'form-xiv-wage-cum-musterroll' => 'CLRA Registers/Sikkim/Form XIV Wage Cum Musterroll.php',
        'form-xiii-wage-register' => 'CLRA Registers/Sikkim/Form XIII Wage Register.php',
    ],

    'Uttar pradesh' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Uttar Pradesh/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/Uttar Pradesh/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Uttar Pradesh/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Uttar Pradesh/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Uttar Pradesh/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Uttar Pradesh/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Uttar Pradesh/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Uttar Pradesh/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Uttar Pradesh/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Uttar Pradesh/MBA Form A_Maternity.php',
        'form-xvii-wage-register' => 'CLRA Registers/Uttar Pradesh/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/Uttar Pradesh/Form XIII.php',
        'form-xvi' => 'CLRA Registers/Uttar Pradesh/Form XVI.php',
        'form-xx' => 'CLRA Registers/Uttar Pradesh/Form XX.php',
        'form-xxi' => 'CLRA Registers/Uttar Pradesh/Form XXI.php',
        'form-xxii' => 'CLRA Registers/Uttar Pradesh/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Uttar Pradesh/Form XXIII.php',
    ],

    'West bengal' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/West Bengal/Form XII_Register Of Contractors.php',
        'form-xiv-employement-card' => 'CLRA Registers/West Bengal/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/West Bengal/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/West Bengal/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/West Bengal/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/West Bengal/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/West Bengal/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/West Bengal/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/West Bengal/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/West Bengal/MBA Form A_Maternity.php',
        'form-xvii-wage-register' => 'CLRA Registers/West Bengal/Form XVII Wage Register.php',
        'form-xiii' => 'CLRA Registers/West Bengal/Form XIII.php',
        'form-xvi' => 'CLRA Registers/West Bengal/Form XVI.php',
        'form-xx' => 'CLRA Registers/West Bengal/Form XX.php',
        'form-xxi' => 'CLRA Registers/West Bengal/Form XXI.php',
        'form-xxii' => 'CLRA Registers/West Bengal/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/West Bengal/Form XXIII.php',
    ],

    'Telangana' => [
        'form-xii-register-of-contractor' => 'CLRA Registers/Telangana/Form XII_Register Of Contractors.php',
        'form-xiii' => 'CLRA Registers/Telangana/Form XIII.php',
        'form-xiv-employement-card' => 'CLRA Registers/Telangana/Form XIV_Employment Card.php',
        'form-xv-service-certificate' => 'CLRA Registers/Telangana/Form XV_Service Certificate.php',
        'form-xix-wage-slip' => 'CLRA Registers/Telangana/Form XIX_Wage Slip.php',
        'form-xvi' => 'CLRA Registers/Telangana/Form XVI.php',
        'form-xxii' => 'CLRA Registers/Telangana/Form XXII.php',
        'form-xxiii' => 'CLRA Registers/Telangana/Form XXIII.php',
        'form-a-employee-register' => 'CLRA Registers/Telangana/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Telangana/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Telangana/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Telangana/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Telangana/ESI Form 11_AccidentBook.php',
        'form-xx' => 'CLRA Registers/Telangana/Form XX.php',
        'form-xxi' => 'CLRA Registers/Telangana/Form XXI.php',
        'form-xvii-register-of-fines' => 'CLRA Registers/Telangana/Form XVII Register of Fine.php',
        'form-xii-integrated-register' => 'CLRA Registers/Telangana/Form II Integrated Register.php',
        'form-xiii-integrated-register' => 'CLRA Registers/Telangana/Form III Integrated Register.php',
    ],

    'Maharashtra' => [
        'form-xiv-employement-card' => 'CLRA Registers/Maharashtra/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Maharashtra/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Maharashtra/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Maharashtra/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Maharashtra/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Maharashtra/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Maharashtra/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Maharashtra/ESI Form 11_AccidentBook.php',
        'form-mba-maternity' => 'CLRA Registers/Maharashtra/MBA Form A_Maternity.php',
        'form-xiii' => 'CLRA Registers/Maharashtra/Form XIII.php',
        'form-ii' => 'CLRA Registers/Maharashtra/Form II_Musterroll Cum Wages.php',
        'form-xii-register-of-contractor' => 'CLRA Registers/Maharashtra/Form XII_Register Of Contractors.php',
        'form-ix' => 'CLRA Registers/Maharashtra/Form IX_Register Of Workmen.php',
        'form-10-overtime' => 'CLRA Registers/Maharashtra/Form 10_Overtime Register.php',
        'form-attendance-card' => 'CLRA Registers/Maharashtra/Form MWA_Attendance Card.php',
    ],

    'Odisha' => [
        'form-xvi' => 'CLRA Registers/Odisha/Form XVI.php',
        'form-xxiii' => 'CLRA Registers/Odisha/Form XXIII.php',
        'form-x-employment-card' => 'CLRA Registers/Odisha/Form X_Employment Card.php',
        'form-xiv-employement-card' => 'CLRA Registers/Odisha/Form XIV_Employment Card.php',
        'form-xix-wage-slip' => 'CLRA Registers/Odisha/Form XIX_Wage Slip.php',
        'form-xv-service-certificate' => 'CLRA Registers/Odisha/Form XV_Service Certificate.php',
        'form-a-employee-register' => 'CLRA Registers/Odisha/Form A_Employee Register.php',
        'form-b-wage-register' => 'CLRA Registers/Odisha/Form B_Wage Register.php',
        'form-c-loan-recoveries' => 'CLRA Registers/Odisha/Form C_Loan Recoveries.php',
        'form-d-attendance-register' => 'CLRA Registers/Odisha/Form D_Attendance Register.php',
        'form-esi' => 'CLRA Registers/Odisha/ESI Form 11_AccidentBook.php',
        'form-xii-register-of-contractor' => 'CLRA Registers/Odisha/Form XII_Register Of Contractors.php',
        'form-ix' => 'CLRA Registers/Odisha/Form IX_Register Of Workmen.php',
        'form-8-service' => 'CLRA Registers/Odisha/Form 8_Service And Leave Account.php',
        'form-12-register' => 'CLRA Registers/Odisha/Form 12_Register Of Workers.php',
        'form-10-combined-musterroll' => 'CLRA Registers/Odisha/Form 10_Combined Musterroll.php',
        'form-xiii-register-of-wage' => 'CLRA Registers/Odisha/Form XIII_Register Of Wages.php',
    ],

];
